### ISSUE TITLE
Doesn't work with Dropwizard 0.8.0 (final)

### ISSUE THREAD

**Issue by carminexx** [federecio/dropwizard-swagger#37] opened 2015-03-06 10:33 UTC
Hi,
I've been using dropwizard-swagger with drop wizard 0.8.0-rc1 and it worked without problems. Now, once updated drop wizard to 0.8.0 (final release), drop wizard-swagger is unable to start, and the entire application crashes.
The problem is in ViewBundle instantiation, because ViewBundle now is a generic class and it's abstract.

The application fails on:
```
bootstrap.addBundle(new SwaggerBundle<MyConfiguration>());
```

With the typical java error that you get when you're trying to instantiate an abstract class:
```
Exception in thread "main" java.lang.InstantiationError: io.dropwizard.views.ViewBundle
	at io.federecio.dropwizard.swagger.SwaggerDropwizard.onInitialize(SwaggerDropwizard.java:47)
	at io.federecio.dropwizard.swagger.SwaggerDropwizard.initialize(SwaggerDropwizard.java:43)
	at io.dropwizard.setup.Bootstrap.addBundle(Bootstrap.java:142)
	at com.my.app.mainclass(mainclass.java:55)
```

**Comment by refresz** [comment] 2015-03-06 11:03
Confirming this as well.

**Comment by carminexx** [comment] 2015-03-06 11:25
Just for information: you can make the application (and dropwizard-swagger) by NOT using SwaggerBundle, but instead a ViewBundle class that extends ViewBundle, and override the method that returns the configuration for views.

Example:
```
 // Add viewbundle with anon class
        bootstrap.addBundle(new ViewBundle<MyConfiguration>()
        {
            @Override
            public ImmutableMap<String, ImmutableMap<String, String>> getViewConfiguration(MyConfiguration myConf)
            {
                return myConf.getViewRendererConfiguration();
            }
        });
```

And, in you configuration.yml:
```
viewRendererConfiguration:
  .ftl:
    strict_syntax: yes
    whitespace_stripping: yes
```

And, again, in ExampleConfiguration.java, you must add:
```
    @NotNull
    private ImmutableMap<String, ImmutableMap<String, String>> viewRendererConfiguration = ImmutableMap.of();

@JsonProperty("viewRendererConfiguration")
    public ImmutableMap<String, ImmutableMap<String, String>> getViewRendererConfiguration() {
        return viewRendererConfiguration;
    }

    @JsonProperty("viewRendererConfiguration")
    public void setViewRendererConfiguration(Map<String, Map<String, String>> viewRendererConfiguration) {
        ImmutableMap.Builder<String, ImmutableMap<String, String>> builder = ImmutableMap.builder();
        for (Map.Entry<String, Map<String, String>> entry : viewRendererConfiguration.entrySet()) {
            builder.put(entry.getKey(), ImmutableMap.copyOf(entry.getValue()));
        }
        this.viewRendererConfiguration = builder.build();
    }
```

Hope this helps!

**Comment by danieljamesscott** [comment] 2015-03-10 09:11
I have the same issue. What can I do to help get this working?

**Comment by carminexx** [comment] 2015-03-10 12:00
@danieljamesscott check my previous answer: https://github.com/federecio/dropwizard-swagger/issues/37#issuecomment-77545000

**Comment by dp1121** [comment] 2015-03-11 20:45
Hi Carminexx,

I followed your post and did following changes -

1 - added snippet below in my application class in initialize method.

bootstrap.addBundle(new ViewBundle<ConferenceConfiguration>()
        {
            @Override
            public ImmutableMap<String, ImmutableMap<String, String>> getViewConfiguration(ConferenceConfiguration myConf)
            {
                return myConf.getViewRendererConfiguration();
            }
        });

2 - added config in yml
3 - already there in my configuration class

I don't see the error anymore and can run the app fine. My issue is I do not see the swagger ui at http://localhost:8080/swagger

Can you please point me to missing link here?

**Comment by alph486** [comment] 2015-03-12 20:54
It sounds like the "main" solution here is to either use 0.7.1 or wait for a supported version to come out for 0.8.0. It's not like its a ton of code mentioned above, but in any case extra stuff that can be avoided when a new release ships.

@federecio is there active development for supporting 0.8.0?

**Comment by alph486** [comment] 2015-03-12 20:55
I think this is a duplicate of #30

**Comment by vultron81** [comment] 2015-03-12 21:40
I made the necessary changes and created a pull request for Dropwizard v0.8.0 support.

**Comment by alph486** [comment] 2015-03-12 21:54
@vultron81 nice :+1:

**Comment by carminexx** [comment] 2015-03-12 23:05
@alph486 Maybe, but only from 0.8.0-rc2 and above. I used it with Dropwizard 0.8.0-rc1 and it worked, it broke only when I upgraded to 0.8.0. I don't know if the problem was also in 0.8.0-rc2/3/4.

@dp1121 Have you checked the access log? It seems like a Jersey problem. How do you instantiate dropwizard-swagger in your main() ?

**Comment by dp1121** [comment] 2015-03-16 13:14
Thanks @ vultron81 and @carminexx  I am past the issue I was having.

**Comment by sergiofagostinho** [comment] 2015-03-18 12:19
Hi, I can't seem to use the workaround @carminexx provided. I followed the instructions and get the following when calling `gradlew run`:

    Exception in thread "main" java.util.ServiceConfigurationError: io.dropwizard.views.ViewRenderer: Provider io.dropwizard.views.freemarker.FreemarkerViewRenderer could not be instantiated

Any ideas?

**Comment by bdbull** [comment] 2015-03-25 16:09
@dp1121 how did you fix your error?  I am able to get my app to run now, but can't see anything at /swagger either.

**Comment by dp1121** [comment] 2015-03-25 16:14
@bdbull I had missed adding swaggerDropwizard.onRun(configuration, environment,"localhost"); to run method within application class. HTH

**Comment by bdbull** [comment] 2015-03-25 19:12
@dp1121 That was it...thanks!!!

**Comment by federecio** [comment] 2015-04-08 06:55
It's great to see all this interaction going on! 

Just FYI I deployed a new release with version 0.6 that provides support for DW 0.8 (thanks to @thiagomoretto and @vultron81 for the help). The README has been updated accordingly.

**Closed by federecio** 2015-04-08 06:55 UTC

**Comment by waldeilson-info** [comment] 2023-03-08 22:17
> Hi, I can't seem to use the workaround @carminexx provided. I followed the instructions and get the following when calling `gradlew run`:
> 
> ```
> Exception in thread "main" java.util.ServiceConfigurationError: io.dropwizard.views.ViewRenderer: Provider io.dropwizard.views.freemarker.FreemarkerViewRenderer could not be instantiated
> ```
> 
> Any ideas?

How did you solve this issue?
